# configs/svm/linear-svm-binary.yaml

usecase: "binary"
start_step: "model"

data_loader:
  good_file: "data/raw/good.csv"
  promo_file: "data/raw/promotional.csv"
  shuffle: false
  save: "loaded_data_binary.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: true
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_binary.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: true
  save: "features_binary.pkl"

model:
  type: linear_svm
  test_size: 0.2
  random_state: 42
  grid_search: true
  param_grid:
    C: [0.1, 1.0, 10.0, 100.0]
    loss: ["hinge", "squared_hinge"]
  save: "model_lsvm_binary.pkl"

evaluation:
  save: "evaluation_lsvm_binary.png"
# 2025-03-07 07:30:41,995 - src.models.support_vector_machine - INFO - Trained LinearSVC model with {'C': 1.0, 'loss': 'hinge'}
# 2025-03-07 07:30:42,002 - src.evaluation - INFO - Accuracy: 96.61%
# 2025-03-07 07:30:42,008 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support

#            0       0.96      0.98      0.97      6044
#            1       0.97      0.95      0.96      4780

#     accuracy                           0.97     10824
#    macro avg       0.97      0.96      0.97     10824
# weighted avg       0.97      0.97      0.97     10824

# 2025-03-07 07:30:42,010 - src.evaluation - INFO - Confusion Matrix:
# [[5893  151]
#  [ 216 4564]]
