# configs/svm/inear-svm-wp-binary.yaml

usecase: "binary"
start_step: "model"

data_loader:
  good_file: "data/wp/good_sample.csv"
  promo_file: "data/wp/promotional_sample.csv"
  neutral_file: "data/wp/neutral_sample.csv"
  shuffle: false
  save: "loaded_data_wp_binary.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: true
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_wp_binary.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: true
  save: "features_wp_binary.pkl"

model:
  type: linear_svm
  test_size: 0.2
  random_state: 42
  grid_search: true
  param_grid:
    C: [0.1, 1.0, 10.0, 100.0]
    loss: ["hinge", "squared_hinge"]
  save: "model_lsvm_wp_binary.pkl"

evaluation:
  save: "evaluation_lsvm_wp_binary.png"
# 2025-03-10 21:53:50,947 - src.models.support_vector_machine - INFO - Trained LinearSVC model with {'C': 0.1, 'loss': 'squared_hinge'}
# 2025-03-10 21:53:50,979 - src.evaluation - INFO - Accuracy: 89.58%
# 2025-03-10 21:53:50,987 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support

#            0       0.91      0.97      0.94      5942
#            1       0.88      0.89      0.89      6060
#            2       0.89      0.82      0.85      5998

#     accuracy                           0.90     18000
#    macro avg       0.90      0.90      0.90     18000
# weighted avg       0.90      0.90      0.89     18000

# 2025-03-10 21:53:50,989 - src.evaluation - INFO - Confusion Matrix:
# [[5756   65  121]
#  [ 129 5423  508]
#  [ 407  646 4945]]
