# configs/svm/inear-svm-wp-binary.yaml

usecase: "binary"
start_step: "model"

data_loader:
  good_file: "data/wp/good_sample.csv"
  promo_file: "data/wp/promotional_sample.csv"
  shuffle: false
  save: "loaded_data_wp_binary.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: false
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_wp_binary.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: true
  save: "features_wp_binary.pkl"

model:
  type: linear_svm
  test_size: 0.2
  random_state: 42
  grid_search: true
  param_grid:
    C: [0.1, 1.0, 10.0, 100.0]
    loss: ["hinge", "squared_hinge"]
  save: "model_lsvm_wp_binary.pkl"

evaluation:
  save: "evaluation_lsvm_wp_binary.png"
# 2025-03-07 07:36:58,517 - src.models.support_vector_machine - INFO - Trained LinearSVC model with {'C': 1.0, 'loss': 'squared_hinge'}
# 2025-03-07 07:36:58,527 - src.evaluation - INFO - Accuracy: 98.09%
# 2025-03-07 07:36:58,533 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support

#            0       0.98      0.98      0.98      5909
#            1       0.98      0.98      0.98      6091

#     accuracy                           0.98     12000
#    macro avg       0.98      0.98      0.98     12000
# weighted avg       0.98      0.98      0.98     12000

# 2025-03-07 07:36:58,535 - src.evaluation - INFO - Confusion Matrix:
# [[5801  108]
#  [ 121 5970]]
