# configs/svm/svm-binary.yaml

usecase: "binary"
start_step: "model"

data_loader:
  good_file: "data/raw/good.csv"
  promo_file: "data/raw/promotional.csv"
  label_change_frac: 0.0
  shuffle: false
  save: "loaded_data_binary.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: true
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_binary.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: true
  save: "features_binary.pkl"

model:
  type: svm
  test_size: 0.2
  random_state: 42
  grid_search: false
  C: 1.0
  kernel: "linear"
  gamma: "scale"
  save: "svm_binary.pkl"

evaluation:
  save: "evaluation_svm_binary.png"
# 2025-03-03 17:15:03,340 - src.evaluation - INFO - Accuracy: 96.62%
# 2025-03-03 17:15:03,345 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support

#            0       0.96      0.98      0.97      6044
#            1       0.97      0.96      0.96      4780

#     accuracy                           0.97     10824
#    macro avg       0.97      0.97      0.97     10824
# weighted avg       0.97      0.97      0.97     10824

# 2025-03-03 17:15:03,349 - src.evaluation - INFO - Confusion Matrix:
# [[5893  151]
#  [ 215 4565]]
