# configs/naive-bayes/naive-bayes-wp-binary.yaml

usecase: "binary"
start_step: "model"

data_loader:
  good_file: "data/wp/good_sample.csv"
  promo_file: "data/wp/promotional_sample.csv"
  shuffle: false
  save: "loaded_data_wp_binary.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: true
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_wp_binary.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: true
  save: "features_wp_binary.pkl"

model:
  type: naive_bayes
  test_size: 0.2
  random_state: 42
  grid_search: true
  param_grid:
    alpha: [0.01, 0.1, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0]
    fit_prior: [true, false]
  save: "model_nb_wp_binary.pkl"

evaluation:
  save: "evaluation_nb_wp_binary.png"
# 2025-03-07 00:35:10,265 - src.models.naive_bayes - INFO - Trained Naive Bayes model with {'alpha': 0.5, 'fit_prior': False}
# 2025-03-07 00:35:10,289 - src.evaluation - INFO - Accuracy: 93.27%
# 2025-03-07 00:35:10,295 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support

#            0       0.92      0.95      0.93      5909
#            1       0.95      0.92      0.93      6091

#     accuracy                           0.93     12000
#    macro avg       0.93      0.93      0.93     12000
# weighted avg       0.93      0.93      0.93     12000

# 2025-03-07 00:35:10,297 - src.evaluation - INFO - Confusion Matrix:
# [[5592  317]
#  [ 491 5600]]
