# configs/log-reg/log-reg-wp-binary.yaml

usecase: "binary"
start_step: "model"

data_loader:
  good_file: "data/wp/good_sample.csv"
  promo_file: "data/wp/promotional_sample.csv"
  shuffle: false
  save: "loaded_data_wp_binary.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: true
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_wp_binary.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: true
  save: "features_wp_binary.pkl"

model:
  type: logistic_regression
  test_size: 0.2
  random_state: 42
  grid_search: true
  param_grid:
    penalty: ["l1", "l2"]
    solver: ["liblinear", "saga"]
    max_iter: [500, 1000]
  save: "model_lr_wp_binary.pkl"

evaluation:
  save: "evaluation_lr_wp_binary.png"
# 2025-03-07 06:37:33,061 - src.models.logistic_regression - INFO - Trained LogisticRegression model with {'max_iter': 1000, 'penalty': 'l1', 'solver': 'liblinear'}
# 2025-03-07 06:37:33,073 - src.evaluation - INFO - Accuracy: 97.96%
# 2025-03-07 06:37:33,079 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support

#            0       0.98      0.98      0.98      5909
#            1       0.98      0.98      0.98      6091

#     accuracy                           0.98     12000
#    macro avg       0.98      0.98      0.98     12000
# weighted avg       0.98      0.98      0.98     12000

# 2025-03-07 06:37:33,081 - src.evaluation - INFO - Confusion Matrix:
# [[5810   99]
#  [ 146 5945]]
