# configs/log-reg/log-reg-augmented.yaml

usecase: "multilabel"
start_step: "model"

data_loader:
  promo_file: "data/raw/augmented_promotional.csv"
  shuffle: false
  save: "loaded_data_augmented.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: true
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_augmented.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: true
  save: "features_augmented.pkl"

model:
  type: logistic_regression
  test_size: 0.2
  random_state: 42
  grid_search: true
  param_grid:
    penalty: ["l1", "l2"]
    solver: ["liblinear", "saga"]
    max_iter: [500, 1000]
  save: "model_lr_augmented.pkl"

evaluation:
  test_data: "data/raw/promotional.csv"
  save: "evaluation_lr_augmented.png"
# 2025-03-12 22:44:27,599 - src.models.logistic_regression - INFO - Trained LogisticRegression model with {'estimator__max_iter': 500, 'estimator__penalty': 'l2', 'estimator__solver': 'liblinear'}
# 2025-03-12 22:44:27,642 - src.evaluation - INFO - Accuracy: 52.99%
# 2025-03-12 22:44:27,653 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support

#            0       0.80      0.75      0.77     18911
#            1       0.25      0.00      0.00      2142
#            2       0.00      0.00      0.00      1496
#            3       0.00      0.00      0.00      1516
#            4       0.44      0.00      0.00      2198

#    micro avg       0.80      0.54      0.64     26263
#    macro avg       0.30      0.15      0.15     26263
# weighted avg       0.63      0.54      0.56     26263
#  samples avg       0.59      0.56      0.57     26263

# 2025-03-12 22:44:27,658 - src.evaluation - INFO - Confusion Matrix:
# [[[ 1297  3629]
#   [ 4791 14120]]

#  [[21692     3]
#   [ 2141     1]]

#  [[22341     0]
#   [ 1496     0]]

#  [[22320     1]
#   [ 1516     0]]

#  [[21634     5]
#   [ 2194     4]]]
