# configs/log-reg/log-reg-binary.yaml

usecase: "binary"
start_step: "model"

data_loader:
  good_file: "data/raw/good.csv"
  promo_file: "data/raw/promotional.csv"
  shuffle: false
  save: "loaded_data_binary.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: true
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_binary.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: true
  save: "features_binary.pkl"

model:
  type: logistic_regression
  test_size: 0.2
  random_state: 42
  grid_search: true
  param_grid:
    penalty: ["l1", "l2"]
    solver: ["liblinear", "saga"]
    max_iter: [500, 1000]
  save: "model_lr_binary.pkl"

evaluation:
  save: "evaluation_lr_binary.png"
# 2025-03-06 23:11:02,890 - src.models.logistic_regression - INFO - Trained LogisticRegression model with {'max_iter': 500, 'penalty': 'l2', 'solver': 'liblinear'}
# 2025-03-06 23:11:02,898 - src.evaluation - INFO - Accuracy: 96.17%
# 2025-03-06 23:11:02,903 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support

#            0       0.96      0.97      0.97      6044
#            1       0.96      0.95      0.96      4780

#     accuracy                           0.96     10824
#    macro avg       0.96      0.96      0.96     10824
# weighted avg       0.96      0.96      0.96     10824

# 2025-03-06 23:11:02,905 - src.evaluation - INFO - Confusion Matrix:
# [[5879  165]
#  [ 250 4530]]
