# configs/log-reg/log-reg-multilabel.yaml

usecase: "multilabel"
start_step: "model"

data_loader:
  promo_file: "data/raw/promotional.csv"
  shuffle: false
  save: "loaded_data_multilabel.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: true
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_multilabel.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: true
  save: "features_multilabel.pkl"

model:
  type: logistic_regression
  test_size: 0.2
  random_state: 42
  grid_search: true
  param_grid:
    penalty: ["l1", "l2"]
    solver: ["liblinear", "saga"]
    max_iter: [500, 1000]
  save: "model_lr_multilabel.pkl"

evaluation:
  save: "evaluation_lr_multilabel.png"
# 2025-03-06 23:30:48,048 - src.models.logistic_regression - INFO - Trained LogisticRegression model with {'estimator__max_iter': 500, 'estimator__penalty': 'l1', 'estimator__solver': 'liblinear'}
# 2025-03-06 23:30:48,057 - src.evaluation - INFO - Accuracy: 72.59%
# 2025-03-06 23:30:48,063 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support

#            0       0.86      0.95      0.90      3792
#            1       0.00      0.00      0.00       401
#            2       0.70      0.25      0.37       292
#            3       0.00      0.00      0.00       308
#            4       0.67      0.39      0.49       439

#    micro avg       0.84      0.74      0.79      5232
#    macro avg       0.44      0.32      0.35      5232
# weighted avg       0.72      0.74      0.72      5232
#  samples avg       0.80      0.77      0.78      5232

# 2025-03-06 23:30:48,065 - src.evaluation - INFO - Confusion Matrix:
# [[[ 374  602]
#   [ 179 3613]]

#  [[4367    0]
#   [ 401    0]]

#  [[4444   32]
#   [ 219   73]]

#  [[4460    0]
#   [ 308    0]]

#  [[4246   83]
#   [ 269  170]]]
