# configs/log-reg/log-reg-augmented.yaml

usecase: "multilabel"
start_step: "model"

data_loader:
  promo_file: "data/raw/augmented_promotional.csv"
  shuffle: false
  save: "loaded_data_augmented.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: true
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_augmented.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: true
  save: "features_augmented.pkl"

model:
  type: logistic_regression
  test_size: 0.2
  random_state: 42
  grid_search: true
  param_grid:
    penalty: ["l1", "l2"]
    solver: ["liblinear", "saga"]
    max_iter: [500, 1000]
  save: "model_lr_augmented.pkl"

evaluation:
  save: "evaluation_lr_augmented.png"
# 2025-03-06 23:19:23,993 - src.models.logistic_regression - INFO - Trained LogisticRegression model with {'estimator__max_iter': 500, 'estimator__penalty': 'l1', 'estimator__solver': 'liblinear'}
# 2025-03-06 23:19:24,011 - src.evaluation - INFO - Accuracy: 55.51%
# 2025-03-06 23:19:24,018 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support

#            0       0.83      0.87      0.85      4591
#            1       0.58      0.12      0.20      1283
#            2       0.78      0.53      0.63       879
#            3       0.68      0.05      0.10       934
#            4       0.75      0.64      0.69      1291

#    micro avg       0.80      0.61      0.69      8978
#    macro avg       0.72      0.44      0.49      8978
# weighted avg       0.76      0.61      0.63      8978
#  samples avg       0.69      0.65      0.66      8978

# 2025-03-06 23:19:24,020 - src.evaluation - INFO - Confusion Matrix:
# [[[2098  840]
#   [ 610 3981]]

#  [[6136  110]
#   [1129  154]]

#  [[6516  134]
#   [ 411  468]]

#  [[6572   23]
#   [ 885   49]]

#  [[5960  278]
#   [ 464  827]]]
