usecase: "multilabel"
start_step: "model"

data_loader:
  good_file: "data/raw/good.csv"
  promo_file: "data/raw/promotional.csv"
  shuffle: false
  save: "loaded_data_multilabel.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: true
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_multilabel.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: true
  save: "features_multilabel.pkl"

# 2025-03-15 23:11:22,417 - src.evaluation - INFO - Evaluating the model.
# 2025-03-15 23:11:23,562 - src.evaluation - INFO - Accuracy: 66.00%
# 2025-03-15 23:11:23,597 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support

#            0       0.86      0.89      0.88      3792
#            1       0.11      0.05      0.07       401
#            2       0.54      0.28      0.37       292
#            3       0.09      0.03      0.05       308
#            4       0.54      0.50      0.52       439

#    micro avg       0.78      0.71      0.74      5232
#    macro avg       0.43      0.35      0.38      5232
# weighted avg       0.72      0.71      0.71      5232
#  samples avg       0.75      0.74      0.73      5232

# 2025-03-15 23:11:23,629 - src.evaluation - INFO - Confusion Matrix:
# [[[ 449  527]
#   [ 430 3362]]

#  [[4211  156]
#   [ 381   20]]

#  [[4406   70]
#   [ 211   81]]
# ...

#  [[4145  184]
#   [ 219  220]]]
# 2025-03-15 23:11:23,777 - src.evaluation - INFO - Evaluation finished.