# configs/glove-test.yaml

usecase: "multilabel"
start_step: "features"
load:
  data_file: "preprocessed_data_nbm.csv"
#   features_file: "features_glove.pkl"
#   model_file: "nb_glove.pkl"

data_loader:
  promo_file: "data/raw/promotional.csv"
  shuffle: false
  save: "loaded_data_nbm.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: false
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_nbm.csv"

features:
  type: glove
  model_name: "glove-wiki-gigaword-100"
  save: "features_glove.pkl"

model:
  type: naive_bayes
  test_size: 0.2
  random_state: 42
  grid_search: false
  alpha: 0.01
  fit_prior: false
  oversampling: true
  save: "nb_glove.pkl"

evaluation:
  save: "evaluation_glove.png"
