start_step: "data_loader"
load:
  data_file: ""
  features_file: ""
  model_file: ""

data_loader:
  good_file: "data/raw/good.csv"
  promo_file: "data/raw/promotional.csv"
  # nrows: 1000
  shuffle: true
  save: "false"
