# configs/linear-svm-multilabel.yaml

usecase: "multilabel"
start_step: "evaluation"

data_loader:
  promo_file: "data/raw/promotional.csv"
  label_change_frac: 0.0
  shuffle: false
  save: "loaded_data_multilabel.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: false
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_multilabel.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: true
  save: "features_multilabel.pkl"

model:
  type: linear_svm
  test_size: 0.2
  random_state: 42
  grid_search: false
  C: 1.0
  save: "linear_svm_multilabel.pkl"

evaluation:
  save: "evaluation_linear_svm_multilabel.png"
# 2025-02-01 00:06:04,798 - src.evaluation - INFO - Accuracy: 69.63%
# 2025-02-01 00:06:04,807 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support
# 
#            0       0.86      0.92      0.89      3792
#            1       0.08      0.01      0.03       401
#            2       0.59      0.28      0.38       292
#            3       0.06      0.00      0.01       308
#            4       0.63      0.46      0.53       439
# 
#    micro avg       0.82      0.73      0.77      5232
#    macro avg       0.45      0.34      0.37      5232
# weighted avg       0.72      0.73      0.72      5232
#  samples avg       0.78      0.76      0.76      5232
# 
# 2025-02-01 00:06:04,812 - src.evaluation - INFO - Confusion Matrix:
# [[[ 414  562]
#   [ 285 3507]]
# 
#  [[4301   66]
#   [ 395    6]]
# 
#  [[4419   57]
#   [ 210   82]]
# 
#  [[4444   16]
#   [ 307    1]]
# 
#  [[4211  118]
#   [ 236  203]]]
