# configs/linear-svm-binary.yaml

usecase: "binary"

# start_step: "features"
# load:
#   data_file: "preprocessed_data_linear_svm_b.csv"
#   features_file: "features_linear_svm_b.pkl"
#   model_file: "linear_svm_b.pkl"

data_loader:
  # good_file: "data/wp/good_sample.csv"
  # promo_file: "data/wp/promotional_sample.csv"
  # neutral_file: "data/wp/neutral_sample.csv"
  good_file: "data/raw/good.csv"
  promo_file: "data/raw/promotional.csv"
  label_change_frac: 0.0
  shuffle: true
  save: "loaded_data_linear_svm_b.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: false
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_linear_svm_b.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: true
  save: "features_linear_svm_b.pkl"

model:
  type: linear_svm
  test_size: 0.2
  random_state: 42
  grid_search: false
  C: 1.0
  save: "linear_svm_b.pkl"

evaluation:
  save: "evaluation_linear_svm_b.png"
