# configs/linear-svm-binary.yaml

usecase: "binary"
start_step: "model"

data_loader:
  good_file: "data/raw/good.csv"
  promo_file: "data/raw/promotional.csv"
  label_change_frac: 0.0
  shuffle: false
  save: "loaded_data_binary.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: false
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_binary.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: true
  save: "features_binary.pkl"

model:
  type: linear_svm
  test_size: 0.2
  random_state: 42
  grid_search: true
  param_grid:
    C: [0.1, 1.0, 10.0, 100.0]
    loss: ["hinge", "squared_hinge"]
  save: "linear_svm_binary.pkl"

evaluation:
  save: "evaluation_linear_svm_binary.png"

# 2025-02-01 22:12:56,992 - src.train - INFO - Training a binary Linear SVM model with grid search.
# 2025-02-01 22:13:17,398 - src.models.support_vector_machine - INFO - Trained LinearSVC model with {'C': 1.0, 'loss': 'hinge'}
# 2025-02-01 22:13:17,399 - src.train - INFO - Model training complete.
# 2025-02-01 22:13:17,401 - src.utils - INFO - Data saved to data/intermediary\linear_svm_binary.pkl.
# 2025-02-01 22:13:17,402 - src.evaluation - INFO - Evaluating the model.
# 2025-02-01 22:13:17,415 - src.evaluation - INFO - Accuracy: 96.66%
# 2025-02-01 22:13:17,423 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support

#            0       0.97      0.97      0.97      6044
#            1       0.97      0.96      0.96      4780

#     accuracy                           0.97     10824
#    macro avg       0.97      0.97      0.97     10824
# weighted avg       0.97      0.97      0.97     10824

# 2025-02-01 22:13:17,428 - src.evaluation - INFO - Confusion Matrix:
# [[5891  153]
#  [ 209 4571]]
