# configs/log-reg-binary.yaml

usecase: "binary"
start_step: "model"

data_loader:
  good_file: "data/raw/good.csv"
  promo_file: "data/raw/promotional.csv"
  shuffle: false
  save: "loaded_data_binary.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: true
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_binary.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: true
  save: "features_binary.pkl"

model:
  type: logistic_regression
  test_size: 0.2
  random_state: 42
  grid_search: false
  penalty: "l1"
  solver: "liblinear"
  max_iter: 500
  save: "log_reg_binary.pkl"

evaluation:
  save: "evaluation_lrb.png"
# 2025-03-03 17:16:41,752 - src.evaluation - INFO - Accuracy: 96.00%
# 2025-03-03 17:16:41,758 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support

#            0       0.96      0.97      0.96      6044
#            1       0.96      0.95      0.95      4780

#     accuracy                           0.96     10824
#    macro avg       0.96      0.96      0.96     10824
# weighted avg       0.96      0.96      0.96     10824

# 2025-03-03 17:16:41,760 - src.evaluation - INFO - Confusion Matrix:
# [[5860  184]
#  [ 249 4531]]
