# configs/log-reg-binary.yaml

usecase: "binary"
start_step: "model"
load:
  data_file: "preprocessed_data_lrb.csv"
  features_file: "features_lrb.pkl"
  # model_file: "naive_bayes_binary.pkl"

data_loader:
  good_file: "data/raw/good.csv"
  promo_file: "data/raw/promotional.csv"
  shuffle: false
  save: "loaded_data_lrb.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: false
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_lrb.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: false
  save: "features_lrb.pkl"

model:
  type: logistic_regression
  test_size: 0.2
  random_state: 42
  grid_search: false
  penalty: "l1"
  solver: "liblinear"
  max_iter: 500
  save: "log_reg_binary.pkl"

evaluation:
  save: "evaluation_lrb.png"
