# configs/log-reg-multilabel.yaml

usecase: "multilabel"
# start_step: "evaluation"

data_loader:
  promo_file: "data/raw/promotional.csv"
  shuffle: false
  save: "loaded_data_lrm.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: false
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_lrm.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: false
  save: "features_lrm.pkl"

model:
  type: logistic_regression
  test_size: 0.2
  random_state: 42
  grid_search: false
  penalty: "l1"
  solver: "liblinear"
  max_iter: 500
  oversampling: false
  save: "log_reg_multilabel.pkl"

evaluation:
  save: "evaluation_lrm.png"
# 2025-01-29 22:59:11,802 - src.evaluation - INFO - Accuracy: 72.46%
# 2025-01-29 22:59:11,808 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support
#
#            0       0.85      0.96      0.90      3792
#            1       0.00      0.00      0.00       401
#            2       0.64      0.18      0.28       292
#            3       0.00      0.00      0.00       308
#            4       0.66      0.37      0.47       439
#
#    micro avg       0.84      0.73      0.78      5232
#    macro avg       0.43      0.30      0.33      5232
# weighted avg       0.71      0.73      0.71      5232
#  samples avg       0.80      0.77      0.78      5232
