# configs/naive-bayes-binary.yaml

usecase: "binary"
# start_step: "evaluation"

data_loader:
  good_file: "data/raw/good.csv"
  promo_file: "data/raw/promotional.csv"
  shuffle: false
  save: "loaded_data_nbb.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: false # didn't change kpis
  remove_numbers: false # removing numbers decreased f1 by 0.01 with max_features 10_000
  remove_whitespace: true
  save: "preprocessed_data_nbb.csv"

features:
  type: tfidf # tfidf higher precision and count higher recall by 0.1 each
  ngram_range: [1, 1] # 1,2 decreased precision by 0.01 and took significantly longer
  max_df: 0.9 # too low decreased f1 by 0.01
  # 0.001 and 0.9 increased recall by 0.01
  min_df: 0.001 # too high decreased f1 significantly
  max_features: 10_000 # 100_000: 0.88 10_000: 0.88 1_000: 0.86 100:0.77
  sublinear_tf: true # increased all kpis by 0.01
  save: "features_nbb.pkl"

model:
  type: naive_bayes
  test_size: 0.2
  random_state: 42
  grid_search: true
  param_grid:
    alpha: [0.01, 0.1, 0.5, 1.0, 1.5, 2.0]
    fit_prior: [true, false]
  save: "naive_bayes_binary.pkl"

evaluation:
  save: "evaluation_nbb.png"
# 2025-01-29 22:53:09,007 - src.evaluation - INFO - Accuracy: 90.91%
# 2025-01-29 22:53:09,012 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support
#
#            0       0.90      0.94      0.92      6044
#            1       0.92      0.87      0.89      4780
#
#     accuracy                           0.91     10824
#    macro avg       0.91      0.91      0.91     10824
# weighted avg       0.91      0.91      0.91     10824
#
# 2025-01-29 22:53:09,013 - src.evaluation - INFO - Confusion Matrix:
# [[5664  380]
#  [ 604 4176]]
