start_step: "data_loader"
data_file: ""
features_file: ""
model_file: ""

data_loader:
    good_file: "data/raw/good.csv"
    promo_file: "data/raw/promotional.csv"
    shuffle: true
    save: "loaded_data"

preprocessing:
    remove_stopwords: true
    apply_stemming: false
    remove_numbers: true
    save: "preprocessed_data"

vectorizer:
    type: tfidf
    max_features: 1000
    ngram_range: "1,1"
    min_df: 1.0
    max_df: 1.0
    save: "features"

naive_bayes:
    alpha: 1.0
    save: "naive_bayes_model"

evaluation:
    save: "naive_bayes_model"
