# configs/naïve-bayes-multilabel.yaml

usecase: "multilabel"
start_step: "data_loader"
load:
  data_file: ""
  features_file: ""
  model_file: ""

data_loader:
  promo_file: "data/raw/promotional.csv"
  shuffle: true
  save: "loaded_data.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: false
  remove_numbers: true
  remove_whitespace: true
  save: "preprocessed_data.csv"
