# configs/naive-bayes-binary.yaml

usecase: "binary"
start_step: "model"

data_loader:
  good_file: "data/raw/good.csv"
  promo_file: "data/raw/promotional.csv"
  shuffle: false
  save: "loaded_data_binary.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: true
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_binary.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: true
  save: "features_binary.pkl"

model:
  type: naive_bayes
  test_size: 0.2
  random_state: 42
  grid_search: true
  param_grid:
    alpha: [0.01, 0.1, 0.5, 1.0, 1.5, 2.0]
    fit_prior: [true, false]
  save: "naive_bayes_binary.pkl"

evaluation:
  save: "evaluation_nbb.png"
# 2025-03-03 17:17:32,750 - src.models.naive_bayes - INFO - Trained Naive Bayes model parameters: alpha=2.0, fit_prior=False
# 2025-03-03 17:17:32,766 - src.evaluation - INFO - Accuracy: 90.88%
# 2025-03-03 17:17:32,771 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support

#            0       0.91      0.93      0.92      6044
#            1       0.91      0.88      0.90      4780

#     accuracy                           0.91     10824
#    macro avg       0.91      0.91      0.91     10824
# weighted avg       0.91      0.91      0.91     10824

# 2025-03-03 17:17:32,773 - src.evaluation - INFO - Confusion Matrix:
# [[5607  437]
#  [ 550 4230]]
