# configs/naive-bayes-binary.yaml

usecase: "binary"
start_step: "data_loader"
# start_step: "evaluation"
# load:
#   data_file: "preprocessed_data_nbb.csv"
#   features_file: "features_nbb.pkl"
#   model_file: "naive_bayes_binary.pkl"

data_loader:
  good_file: "data/raw/good.csv"
  promo_file: "data/raw/promotional.csv"
  shuffle: true
  save: "loaded_data_nbb.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: false # didn't change kpis
  apply_stemming: false # didn't change kpis
  remove_numbers: false # removing numbers decreased f1 by 0.01 with max_features 10_000
  remove_whitespace: true
  save: "preprocessed_data_nbb.csv"

features:
  type: tfidf # tfidf higher precision and count higher recall by 0.1 each
  max_features: 10_000 # 100_000: 0.88 10_000: 0.88 1_000: 0.86 100:0.77
  ngram_range: [1, 1] # 1,2 decreased precision by 0.01 and took significantly longer
  min_df: 0.001 # too high decreased f1 significantly
  max_df: 0.9 # too low decreased f1 by 0.01
  # 0.001 and 0.9 increased recall by 0.01
  sublinear_tf: true # increased all kpis by 0.01
  save: "features_nbb.pkl"

model:
  type: naive_bayes
  test_size: 0.2
  random_state: 42
  alpha: 1.0 # 0.5 decreased recall by 0.1 above 1 decreased precision by 0.1
  save: "naive_bayes_binary.pkl"

evaluation:
  save: "evaluation_nbb.png"
