# configs/naïve-bayes-multilabel.yaml

usecase: "multilabel"
start_step: "data_loader"
# start_step: "evaluation"
# load:
#   data_file: "preprocessed_data_nbm.csv"
#   features_file: "features_nbm.pkl"
#   model_file: "naive_bayes_multilabel.pkl"

data_loader:
  promo_file: "data/raw/promotional.csv"
  shuffle: true
  save: "loaded_data_nbm.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: false
  remove_numbers: true
  remove_whitespace: true
  save: "preprocessed_data_nbm.csv"

features:
  type: tfidf
  max_features: 10_000
  ngram_range: [1, 1]
  min_df: 0.01
  max_df: 1.0
  sublinear_tf: true
  save: "features_nbm.pkl"

model:
  type: naive_bayes
  test_size: 0.2
  random_state: 42
  alpha: 1.0
  oversampling: true
  save: "naive_bayes_multilabel.pkl"

evaluation:
  save: "evaluation_nbm.png"
