# configs/svm-augmented.yaml

usecase: "multilabel"
start_step: "model"

data_loader:
  promo_file: "data/raw/augmented_promotional.csv"
  label_change_frac: 0.0
  shuffle: false
  save: "loaded_data_augmented.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: true
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_augmented.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: true
  save: "features_augmented.pkl"

model:
  type: svm
  test_size: 0.2
  random_state: 42
  grid_search: false
  C: 1.0
  kernel: "linear"
  save: "svm_augmented.pkl"

evaluation:
  save: "evaluation_svm_multilabel.png"
# 2025-03-04 13:56:16,192 - src.evaluation - INFO - Accuracy: 61.20%
# 2025-03-04 13:56:16,198 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support

#            0       0.86      0.88      0.87      4591
#            1       0.80      0.23      0.36      1283
#            2       0.86      0.69      0.77       879
#            3       0.90      0.12      0.22       934
#            4       0.81      0.77      0.79      1291

#    micro avg       0.85      0.67      0.75      8978
#    macro avg       0.85      0.54      0.60      8978
# weighted avg       0.85      0.67      0.71      8978
#  samples avg       0.75      0.70      0.71      8978

# 2025-03-04 13:56:16,201 - src.evaluation - INFO - Confusion Matrix:
# [[[2286  652]
#   [ 572 4019]]

#  [[6171   75]
#   [ 984  299]]

#  [[6554   96]
#   [ 275  604]]

#  [[6583   12]
#   [ 820  114]]

#  [[6010  228]
#   [ 301  990]]]
