# configs/svm-multilabel.yaml

usecase: "multilabel"
start_step: "evaluation"

data_loader:
  promo_file: "data/raw/promotional.csv"
  label_change_frac: 0.0
  shuffle: false
  save: "loaded_data_multilabel.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: false
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_multilabel.csv"

features:
  type: tfidf
  ngram_range: [1, 1]
  max_df: 0.9
  min_df: 0.001
  max_features: 10_000
  sublinear_tf: true
  save: "features_multilabel.pkl"

model:
  type: svm
  test_size: 0.2
  random_state: 42
  grid_search: false
  C: 1.0
  kernel: "linear"
  save: "svm_multilabel.pkl"

evaluation:
  save: "evaluation_svm_multilabel.png"
# 2025-02-01 12:12:24,027 - src.evaluation - INFO - Accuracy: 72.71%
# 2025-02-01 12:12:24,034 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support
# 
#            0       0.86      0.95      0.90      3792
#            1       0.00      0.00      0.00       401
#            2       0.78      0.25      0.38       292
#            3       0.00      0.00      0.00       308
#            4       0.69      0.44      0.53       439
# 
#    micro avg       0.85      0.74      0.79      5232
#    macro avg       0.47      0.33      0.36      5232
# weighted avg       0.72      0.74      0.72      5232
#  samples avg       0.81      0.77      0.78      5232
# 
# 2025-02-01 12:12:24,039 - src.evaluation - INFO - Confusion Matrix:
# [[[ 381  595]
#   [ 192 3600]]
# 
#  [[4367    0]
#   [ 401    0]]
# 
#  [[4455   21]
#   [ 218   74]]
# 
#  [[4460    0]
#   [ 308    0]]
# 
#  [[4243   86]
#   [ 248  191]]]
