# configs/vec-test/w2v-test.yaml

usecase: "multilabel"
# start_step: "evaluation"

data_loader:
  promo_file: "data/raw/promotional.csv"
  shuffle: false
  save: "loaded_data_nbm.csv"

preprocessing:
  remove_non_word: true
  convert_lowercase: true
  remove_stopwords: true
  apply_stemming: false
  remove_numbers: false
  remove_whitespace: true
  save: "preprocessed_data_nbm.csv"

features:
  type: word2vec
  workers: 32
  vector_size: 100
  window: 5
  min_count: 5
  sg: 0
  hs: 0
  negative: 5
  alpha: 0.025
  epochs: 1
  save: "features_w2v.pkl"

model:
  type: naive_bayes
  test_size: 0.2
  random_state: 42
  grid_search: false
  alpha: 0.01
  fit_prior: false
  oversampling: true
  save: "nb_w2v.pkl"

evaluation:
  save: "evaluation_w2v.png"
# 2025-01-29 22:56:13,096 - src.evaluation - INFO - Accuracy: 36.22%
# 2025-01-29 22:56:13,102 - src.evaluation - INFO - Classification Report:
#               precision    recall  f1-score   support
#
#            0       0.92      0.75      0.83      3773
#            1       0.13      0.59      0.21       430
#            2       0.25      0.85      0.39       296
#            3       0.10      0.50      0.17       332
#            4       0.33      0.85      0.47       415
#
#    micro avg       0.44      0.73      0.55      5246
#    macro avg       0.35      0.71      0.41      5246
# weighted avg       0.72      0.73      0.68      5246
#  samples avg       0.55      0.74      0.60      5246
