preprocessing:
    remove_stopwords: true
    apply_stemming: false
    remove_numbers: true

vectorizer:
    type: tfidf
    max_features: 1000
    ngram_range: "1,1"
    min_df: 1.0
    max_df: 1.0

naive_bayes:
    alpha: 1.0
